version: '3.8'
services:
  app:
    profiles: ['all']
    image: ...
    build:
      context: build
      args:
        ARG=arg
    container_name: app
    ports:
      - 8080:8080
    volumes:
      - ./:/app
      - volume:/data
    restart: always
    entrypoint: /bin/bash
    command: -c ls
    working_dir: /app
    environment:
      PARAM=foo
    env_file:
      - app.env
    depends_on:
      - db

volumes:
  - volume

networks:
  default:
